[project]
name = "lucerna"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "gitpython>=3.1.45",
    "interrogate>=1.7.0",
    "pandas>=2.3.3",
    "pip>=25.3",
    "pygount>=3.1.0",
    "seaborn>=0.13.2",
]
